export const MEXICO_STATES = [
  { label: "Aguascalientes", value: "Aguascalientes" },
  { label: "Baja California", value: "Baja California" },
  { label: "Baja California Sur", value: "Baja California Sur" },
  { label: "Campeche", value: "Campeche" },
  { label: "Chiapas", value: "Chiapas" },
  { label: "Chihuahua", value: "Chihuahua" },
  { label: "Coahuila de Zaragoza", value: "Coahuila de Zaragoza" },
  { label: "Colima", value: "Colima" },
  { label: "Ciudad de México", value: "Ciudad de México" },
  { label: "Durango", value: "Durango" },
  { label: "Guanajuato", value: "Guanajuato" },
  { label: "Guerrero", value: "Guerrero" },
  { label: "Hidalgo", value: "Hidalgo" },
  { label: "Jalisco", value: "Jalisco" },
  { label: "Mexico", value: "Mexico" },
  { label: "Michoacan de Ocampo", value: "Michoacan de Ocampo" },
  { label: "Morelos", value: "Morelos" },
  { label: "Nayarit", value: "Nayarit" },
  { label: "Nuevo Leon", value: "Nuevo Leon" },
  { label: "Oaxaca", value: "Oaxaca" },
  { label: "Puebla", value: "Puebla" },
  { label: "Queretaro de Arteaga", value: "Queretaro de Arteaga" },
  { label: "Quintana Roo", value: "Quintana Roo" },
  { label: "San Luis Potosi", value: "San Luis Potosi" },
  { label: "Sinaloa", value: "Sinaloa" },
  { label: "Sonora", value: "Sonora" },
  { label: "Tabasco", value: "Tabasco" },
  { label: "Tamaulipas", value: "Tamaulipas" },
  { label: "Tlaxcala", value: "Tlaxcala" },
  { label: "Veracruz-Llave", value: "Veracruz-Llave" },
  { label: "Yucatan", value: "Yucatan" },
  { label: "Zacatecas", value: "Zacatecas" },
];
